version: "3"

services:
  nginx:
    build: deployment/nginx
#    image: "jinaai/now-nginx:latest"
    ports:
      - 80:80
    depends_on:
      - bff
      - playground
  bff:
    build: deployment/bff
#    image: "jinaai/now-bff:latest"
  playground:
    build: deployment/playground
#    image: "jinaai/now-playground:latest"
    depends_on:
      - bff
