apiVersion: apps/v1
kind: Deployment
metadata:
  name: now-frontend
  namespace: nowapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: now-frontend
  template:
    metadata:
      labels:
        app: now-frontend
    spec:
      containers:
        - name: now-frontend
#          image: jinaai/now-frontend:{docker_frontend_tag}
          image: jinaaitmpjoschka/now-frontend:latest
          imagePullPolicy: Always
          command: ["streamlit"]
          args: ["run", "frontend.py", "--server.port", "80"]
#          args: ["run", "frontend.py", "--server.port", "80", "{gateway_host}", "{gateway_port}", "{output_modality}", "{data}"]
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: now-bff
  namespace: nowapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: now-bff
  template:
    metadata:
      labels:
        app: now-bff
    spec:
      containers:
        - name: now-bff
          image: jinaaitmpjoschka/now-bff:latest
          imagePullPolicy: Always
          command: ['uvicorn']
          args:  ["deployment.bff.app.app:application", "--host", "0.0.0.0", "--port", "80", "--loop", "uvloop", "--root-path", "/api"]
          ports:
            - containerPort: 80
